name: Sync Labels

on:
  push:
    branches: [ main ]
    paths:
      - .github/labels.yml
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      metadata: read
    steps:
      - uses: actions/checkout@v4
      - name: Sync GitHub Labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml_file: .github/labels.yml
          skip_delete: false

